// flow-typed signature: 050e782c72e1d1d77c540515438cb275
// flow-typed version: <<STUB>>/react-native-haptic-feedback_v1.11.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-haptic-feedback'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-haptic-feedback' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'react-native-haptic-feedback/index' {
  declare module.exports: $Exports<'react-native-haptic-feedback'>;
}
declare module 'react-native-haptic-feedback/index.js' {
  declare module.exports: $Exports<'react-native-haptic-feedback'>;
}
